import 'package:flutter_sixvalley_ecommerce/features/create_auction/domain/models/add_auction_product_model.dart';
import 'package:flutter_sixvalley_ecommerce/features/create_auction/domain/repository/add_auction_product_repository_interface.dart';
import 'package:flutter_sixvalley_ecommerce/features/create_auction/domain/services/add_auction_product_service_interface.dart';
import 'package:image_picker/image_picker.dart';


class AddAuctionProductService implements AddAuctionProductServiceInterface {
  final AddAuctionProductRepositoryInterface auctionRepoInterface;
  AddAuctionProductService({required this.auctionRepoInterface});

  @override
  Future addAuctionProduct({
    required AddAuctionProductModel addAuctionProduct,
    required int categoryId,
    int? brandId,
    required String productType,
    required String itemCondition,
    required double entryFee,
    required double startingPrice,
    required double minimumIncrementAmount,
    required double maximumDecrementAmount,
    required String startTime,
    required String endTime,
    int? duration,
    required int status,
    required double shippingFee,
    String? returnPolicy,
    required XFile thumbnail,
    required List<XFile> images,
    String? videoType,
    String? youtubeVideo,
    XFile? customerVideo,
    List<int>? taxIds,
    String? tags,
    String? metaTitle,
    String? metaDescription,
    String? metaIndex,
    String? metaNoFollow,
    String? metaNoImageIndex,
    String? metaNoArchive,
    String? metaNoSnippet,
    String? metaMaxSnippet,
    String? metaMaxSnippetValue,
    String? metaMaxVideoPreview,
    String? metaMaxVideoPreviewValue,
    String? metaMaxImagePreview,
    String? metaMaxImagePreviewValue,
    XFile? metaImage,
    String? currentCurrencyCode,
  }) async {
    return await auctionRepoInterface.addAuctionProduct(
      addAuctionProduct: addAuctionProduct,
      categoryId: categoryId,
      brandId: brandId,
      productType: productType,
      itemCondition: itemCondition,
      entryFee: entryFee,
      startingPrice: startingPrice,
      minimumIncrementAmount: minimumIncrementAmount,
      maximumDecrementAmount: maximumDecrementAmount,
      startTime: startTime,
      endTime: endTime,
      duration: duration,
      status: status,
      shippingFee: shippingFee,
      returnPolicy: returnPolicy,
      thumbnail: thumbnail,
      images: images,
      videoType: videoType,
      youtubeVideo: youtubeVideo,
      customerVideo: customerVideo,
      taxIds: taxIds,
      tags: tags,
      metaTitle: metaTitle,
      metaDescription: metaDescription,
      metaIndex: metaIndex,
      metaNoFollow: metaNoFollow,
      metaNoImageIndex: metaNoImageIndex,
      metaNoArchive: metaNoArchive,
      metaNoSnippet: metaNoSnippet,
      metaMaxSnippet: metaMaxSnippet,
      metaMaxSnippetValue: metaMaxSnippetValue,
      metaMaxVideoPreview: metaMaxVideoPreview,
      metaMaxVideoPreviewValue: metaMaxVideoPreviewValue,
      metaMaxImagePreview: metaMaxImagePreview,
      metaMaxImagePreviewValue: metaMaxImagePreviewValue,
      metaImage: metaImage,
      currentCurrencyCode: currentCurrencyCode,
    );
  }

  @override
  Future updateAuctionProduct({
    required int productId,
    required AddAuctionProductModel addAuctionProduct,
    required int categoryId,
    int? brandId,
    required String productType,
    required String itemCondition,
    required double entryFee,
    required double startingPrice,
    required double minimumIncrementAmount,
    required double maximumDecrementAmount,
    required String startTime,
    required String endTime,
    int? duration,
    required int status,
    required double shippingFee,
    String? returnPolicy,
    XFile? thumbnail,
    List<XFile>? images,
    String? videoType,
    String? youtubeVideo,
    XFile? customerVideo,
    List<int>? taxIds,
    String? tags,
    String? metaTitle,
    String? metaDescription,
    String? metaIndex,
    String? metaNoFollow,
    String? metaNoImageIndex,
    String? metaNoArchive,
    String? metaNoSnippet,
    String? metaMaxSnippet,
    String? metaMaxSnippetValue,
    String? metaMaxVideoPreview,
    String? metaMaxVideoPreviewValue,
    String? metaMaxImagePreview,
    String? metaMaxImagePreviewValue,
    XFile? metaImage,
    String? currentCurrencyCode,
  }) async {
    return await auctionRepoInterface.updateAuctionProduct(
      productId: productId,
      addAuctionProduct: addAuctionProduct,
      categoryId: categoryId,
      brandId: brandId,
      productType: productType,
      itemCondition: itemCondition,
      entryFee: entryFee,
      startingPrice: startingPrice,
      minimumIncrementAmount: minimumIncrementAmount,
      maximumDecrementAmount: maximumDecrementAmount,
      startTime: startTime,
      endTime: endTime,
      duration: duration,
      status: status,
      shippingFee: shippingFee,
      returnPolicy: returnPolicy,
      thumbnail: thumbnail,
      images: images,
      videoType: videoType,
      youtubeVideo: youtubeVideo,
      customerVideo: customerVideo,
      taxIds: taxIds,
      tags: tags,
      metaTitle: metaTitle,
      metaDescription: metaDescription,
      metaIndex: metaIndex,
      metaNoFollow: metaNoFollow,
      metaNoImageIndex: metaNoImageIndex,
      metaNoArchive: metaNoArchive,
      metaNoSnippet: metaNoSnippet,
      metaMaxSnippet: metaMaxSnippet,
      metaMaxSnippetValue: metaMaxSnippetValue,
      metaMaxVideoPreview: metaMaxVideoPreview,
      metaMaxVideoPreviewValue: metaMaxVideoPreviewValue,
      metaMaxImagePreview: metaMaxImagePreview,
      metaMaxImagePreviewValue: metaMaxImagePreviewValue,
      metaImage: metaImage,
      currentCurrencyCode: currentCurrencyCode,
    );
  }

  @override
  Future deleteAuctionProduct({required int productId}) async {
    return await auctionRepoInterface.deleteAuctionProduct(productId: productId);
  }

  @override
  Future cancelAuctionProduct({required int productId}) async {
    return await auctionRepoInterface.cancelAuctionProduct(productId: productId);
  }

  @override
  Future relaunchAuction({
    required int auctionId,
    required AddAuctionProductModel addAuctionProduct,
    required int categoryId,
    int? brandId,
    required String productType,
    required String itemCondition,
    required double entryFee,
    required double startingPrice,
    required double minimumIncrementAmount,
    required double maximumDecrementAmount,
    required String startTime,
    required String endTime,
    int? duration,
    required int status,
    required double shippingFee,
    String? returnPolicy,
    XFile? thumbnail,
    List<XFile>? images,
    String? videoType,
    String? youtubeVideo,
    XFile? customerVideo,
    List<int>? taxIds,
    String? tags,
    String? metaTitle,
    String? metaDescription,
    String? metaIndex,
    String? metaNoFollow,
    String? metaNoImageIndex,
    String? metaNoArchive,
    String? metaNoSnippet,
    String? metaMaxSnippet,
    String? metaMaxSnippetValue,
    String? metaMaxVideoPreview,
    String? metaMaxVideoPreviewValue,
    String? metaMaxImagePreview,
    String? metaMaxImagePreviewValue,
    XFile? metaImage,
    String? currentCurrencyCode,
  }) async {
    return await auctionRepoInterface.relaunchAuction(
      auctionId: auctionId,
      addAuctionProduct: addAuctionProduct,
      categoryId: categoryId,
      brandId: brandId,
      productType: productType,
      itemCondition: itemCondition,
      entryFee: entryFee,
      startingPrice: startingPrice,
      minimumIncrementAmount: minimumIncrementAmount,
      maximumDecrementAmount: maximumDecrementAmount,
      startTime: startTime,
      endTime: endTime,
      duration: duration,
      status: status,
      shippingFee: shippingFee,
      returnPolicy: returnPolicy,
      thumbnail: thumbnail,
      images: images,
      videoType: videoType,
      youtubeVideo: youtubeVideo,
      customerVideo: customerVideo,
      taxIds: taxIds,
      tags: tags,
      metaTitle: metaTitle,
      metaDescription: metaDescription,
      metaIndex: metaIndex,
      metaNoFollow: metaNoFollow,
      metaNoImageIndex: metaNoImageIndex,
      metaNoArchive: metaNoArchive,
      metaNoSnippet: metaNoSnippet,
      metaMaxSnippet: metaMaxSnippet,
      metaMaxSnippetValue: metaMaxSnippetValue,
      metaMaxVideoPreview: metaMaxVideoPreview,
      metaMaxVideoPreviewValue: metaMaxVideoPreviewValue,
      metaMaxImagePreview: metaMaxImagePreview,
      metaMaxImagePreviewValue: metaMaxImagePreviewValue,
      metaImage: metaImage,
      currentCurrencyCode: currentCurrencyCode,
    );
  }
}
